---
- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    engine_url: https://ovirt-engine.example.com/ovirt-engine/api
    engine_user: admin@internal
    engine_cafile: ca.pem
    vm_template: centos7
    uxdatacenter: Default
    uxcluster: Default
    uxsd: virtualmachines
    uxprefix: ovirtdemo

    httpd_vm:
      cluster: "{{ uxcluster }}"
      template: "{{ vm_template }}"
      memory: 2GiB
      memory_guaranteed: 2GiB
      cores: 2
      disks:
        - size: 10GiB
          name: data
          storage_domain: "{{ uxsd }}"
          interface: virtio

    db_vm:
      cluster: "{{ uxcluster }}"
      template: "{{ vm_template }}"
      memory: 2GiB
      memory_guaranteed: 2GiB
      cores: 1
      disks:
        - size: 10GiB
          name: data
          storage_domain: "{{ uxsd }}"
          interface: virtio
      nics:
        - name: ovirtmgmt
          network: ovirtmgmt
          profile: ovirtmgmt

    vms:
      - name: "{{ uxprefix }}-postgresql-vm"
        tag: postgresql_vm
        profile: "{{ db_vm }}"
      - name: "{{ uxprefix }}-apache-vm"
        tag: httpd_vm
        profile: "{{ httpd_vm }}"

  roles:
    - oVirt.vm-infra
